name: CI Docker

on:
    workflow_call:
        inputs:
            build_context:
                description: "Path to the Docker build context"
                required: true
                type: string
            dockerfile:
                description: "Path to the Dockerfile"
                required: true
                type: string
            image_suffix:
                description: "Suffix for the image name (e.g., kgcode-ide)"
                required: true
                type: string
            release_branch:
                description: "Branch to trigger release pushes"
                required: false
                default: "master"
                type: string
            build_args:
                description: "Docker build args, comma-separated e.g. WS_HOST=host,API_KEY=abc"
                required: false
                default: ""
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Envs
              run: |
                  SHOULD_RELEASE=$( [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/${{ inputs.release_branch }}" ] && echo true || echo false )
                  echo "SHOULD_RELEASE=${SHOULD_RELEASE}" >> $GITHUB_ENV
                  echo "VERSION=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

            - name: Format Build Args
              id: format-args
              run: |
                  if [ -n "${{ inputs.build_args }}" ]; then
                      FORMATTED_ARGS=$(echo "${{ inputs.build_args }}" | tr ',' '\n')
                      echo "FORMATTED_ARGS<<EOF" >> $GITHUB_ENV
                      echo "$FORMATTED_ARGS" >> $GITHUB_ENV
                      echo "EOF" >> $GITHUB_ENV
                  else
                      echo "FORMATTED_ARGS=" >> $GITHUB_ENV
                  fi

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Builder
              uses: docker/setup-buildx-action@v3

            - name: Log into GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ${{ inputs.build_context }}
                  file: ${{ inputs.dockerfile }}
                  push: ${{ env.SHOULD_RELEASE }}
                  build-args: ${{ env.FORMATTED_ARGS }}
                  tags: |
                      ghcr.io/${{ github.repository }}/${{ inputs.image_suffix }}:latest
                      ghcr.io/${{ github.repository }}/${{ inputs.image_suffix }}:${{ env.VERSION }}
