name: Sync Branches

on:
    workflow_call:
        inputs:
            source_branch:
                description: "Branch to merge from"
                required: false
                type: string
            target_branch:
                description: "Branch to merge into"
                required: false
                type: string
            conflict_paths:
                description: "Paths (folders/files) to resolve in favor of target branch (space-separated)"
                required: false
                default: ""
                type: string

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Fetch target branch
              run: git fetch origin ${{ inputs.target_branch }}:${{ inputs.target_branch }}

            - name: Merge source into target with custom message
              run: |
                  git checkout ${{ inputs.target_branch }}
                  git merge --no-commit --no-ff origin/${{ inputs.source_branch }} || true

                  if [ -n "${{ inputs.conflict_paths }}" ]; then
                      git checkout --ours ${{ inputs.conflict_paths }} || true
                      git add ${{ inputs.conflict_paths }} || true
                  fi

                  if ! git diff --check; then
                      echo "Merge conflicts remain, aborting."
                      exit 1
                  fi

                  MSGS="$(git log --pretty=format:'%s' ${{ inputs.target_branch }}..origin/${{ inputs.source_branch }})"

                  if [ -n "$MSGS" ]; then
                      git commit -m "sync: merged commits from ${{ inputs.source_branch }} into ${{ inputs.target_branch }}" -m "$MSGS"
                  else
                      echo "Nothing to commit"
                  fi

            - name: Push changes
              run: git push origin ${{ inputs.target_branch }}
